// Random NFL team data that is added to Firestore
// After you've signed into NFL Teams Hub, click the dropdown
// menu in the top right corner and select "Add random data"

export const randomData = {
  teamNames: [
    "Kansas City Chiefs",
    "Buffalo Bills",
    "Miami Dolphins",
    "New England Patriots",
    "New York Jets",
    "Baltimore Ravens",
    "Cincinnati Bengals",
    "Cleveland Browns",
    "Pittsburgh Steelers",
    "Houston Texans",
    "Indianapolis Colts",
    "Jacksonville Jaguars",
    "Tennessee Titans",
    "Denver Broncos",
    "Las Vegas Raiders",
    "Los Angeles Chargers",
    "Dallas Cowboys",
    "New York Giants",
    "Philadelphia Eagles",
    "Washington Commanders",
    "Chicago Bears",
    "Detroit Lions",
    "Green Bay Packers",
    "Minnesota Vikings",
    "Atlanta Falcons",
    "Carolina Panthers",
    "New Orleans Saints",
    "Tampa Bay Buccaneers",
    "Arizona Cardinals",
    "Los Angeles Rams",
    "San Francisco 49ers",
    "Seattle Seahawks",
  ],
  teamCities: [
    "Kansas City",
    "Buffalo",
    "Miami",
    "Boston",
    "New York",
    "Baltimore",
    "Cincinnati",
    "Cleveland",
    "Pittsburgh",
    "Houston",
    "Indianapolis",
    "Jacksonville",
    "Nashville",
    "Denver",
    "Las Vegas",
    "Los Angeles",
    "Dallas",
    "Philadelphia",
    "Washington",
    "Chicago",
    "Detroit",
    "Green Bay",
    "Minneapolis",
    "Atlanta",
    "Charlotte",
    "New Orleans",
    "Tampa Bay",
    "Phoenix",
    "San Francisco",
    "Seattle",
  ],
  teamConferences: [
    "AFC",
    "NFC",
  ],
  teamDivisions: [
    "AFC East",
    "AFC North",
    "AFC South",
    "AFC West",
    "NFC East",
    "NFC North",
    "NFC South",
    "NFC West",
  ],
  teamDiscussions: [
    { text: "This team is absolutely incredible this season!", rating: 5 },
    { text: "Amazing performance and great coaching!", rating: 5 },
    { text: "The players are so talented and dedicated.", rating: 5 },
    { text: "Great team chemistry and fan support.", rating: 5 },
    { text: "A championship-caliber team!", rating: 5 },
    {
      text: "Outstanding plays that left me speechless.",
      rating: 5,
    },
    { text: "Perfect execution and strategic gameplay.", rating: 5 },
    { text: "Incredible defense and explosive offense.", rating: 5 },
    { text: "Good team, solid performance overall.", rating: 4 },
    { text: "Enjoyed watching them play, would support again.", rating: 4 },
    { text: "Decent roster and reasonable expectations.", rating: 4 },
    { text: "Friendly fanbase, but the team was just okay.", rating: 3 },
    { text: "Decent season, but nothing extraordinary.", rating: 3 },
    { text: "The team was average, could be better.", rating: 3 },
    {
      text: "Coaching was questionable, and the plays were disappointing.",
      rating: 2,
    },
    { text: "Expected more, but left unsatisfied.", rating: 2 },
    { text: "Underwhelming performance and strategy.", rating: 2 },
    { text: "Disappointing season overall.", rating: 2 },
    {
      text: "The team was terrible, will never support again.",
      rating: 1,
    },
    {
      text: "Worst team performance I've seen so far.",
      rating: 1,
    },
    { text: "Avoid this team, the gameplay was unwatchable.", rating: 1 },
    { text: "Unpleasant fan experience and poor management.", rating: 1 },
    { text: "Simply outstanding! A championship team.", rating: 5 },
    { text: "Couldn't get enough of the amazing plays.", rating: 5 },
    { text: "Top-notch talent, worth every game ticket.", rating: 5 },
    { text: "Highly recommended for football fans.", rating: 5 },
    { text: "Exquisite gameplay that pleased my football appetite.", rating: 5 },
    { text: "A gem of a team, impeccable in every aspect.", rating: 5 },
    { text: "Excellent roster and coaching staff.", rating: 5 },
    { text: "A fantastic football experience overall.", rating: 5 },
    {
      text: "The stadium atmosphere was electric, perfect for game day.",
      rating: 4,
    },
    { text: "Good team, but the coaching could be improved.", rating: 4 },
    {
      text: "Pleasantly surprised by the variety of plays.",
      rating: 4,
    },
    { text: "Well-coached team and dedicated players.", rating: 4 },
    { text: "Satisfying games, suitable for casual viewing.", rating: 4 },
    { text: "The team was okay, nothing special.", rating: 3 },
    {
      text: "Coaching could be better, but the talent was fine.",
      rating: 3,
    },
    {
      text: "An average season, didn't leave a lasting impression.",
      rating: 3,
    },
    { text: "Expected more value for the season tickets.", rating: 2 },
    { text: "Mediocre performance and lackluster strategy.", rating: 2 },
    {
      text: "Regret spending money on such a disappointing season.",
      rating: 2,
    },
    { text: "Not up to par with my expectations.", rating: 2 },
  ],
};
